# Generated by Django 4.2.6 on 2024-01-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('department_location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('MiddleName', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('Employee_type', models.CharField(choices=[('Hourly', 'Hourly Employee'), ('Salaried', 'Salaried Employee'), ('Contract', 'Contract Employee')], max_length=10, null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('birthdate', models.DateField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublejay.department')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('ProjectLocation', models.CharField(max_length=200)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublejay.department')),
            ],
        ),
        migrations.CreateModel(
            name='Works_on',
            fields=[
                ('work_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublejay.employee')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublejay.department')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublejay.project')),
            ],
        ),
        migrations.CreateModel(
            name='Salaried_Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnualSalary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('StockOption', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublejay.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HourlyRate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublejay.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('Dependent_id', models.AutoField(primary_key=True, serialize=False)),
                ('Dependent_Name', models.CharField(max_length=255)),
                ('Dependent_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('Dependent_birthdate', models.DateField()),
                ('Dependent_Relationship', models.CharField(max_length=255)),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublejay.employee')),
            ],
        ),
        migrations.CreateModel(
            name='department_Employee',
            fields=[
                ('EmployeeDepartment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=50)),
                ('Employee_type', models.CharField(choices=[('Hourly', 'Hourly Employee'), ('Salaried', 'Salaried Employee'), ('Contract', 'Contract Employee')], max_length=10, null=True)),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublejay.employee')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublejay.department')),
            ],
        ),
        migrations.CreateModel(
            name='Contract_consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillingRate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Contract_number', models.CharField(max_length=7)),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doublejay.employee')),
            ],
        ),
    ]
