# Generated by Django 4.2.6 on 2024-01-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublejay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works_on',
            name='work_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
