# Generated by Django 4.2.6 on 2024-01-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublejay', '0002_alter_works_on_work_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_id',
            field=models.CharField(default='E612', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
