# Generated by Django 4.2.6 on 2024-02-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublejay', '0011_alter_dependent_dependent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='Dependent_id',
            field=models.CharField(default='DE403', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_id',
            field=models.CharField(default='E977', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hourlyemployee',
            name='HourlyRate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(default='P053', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salaried_employee',
            name='AnnualSalary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaried_employee',
            name='StockOption',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='works_on',
            name='work_id',
            field=models.CharField(default='W548', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
